name: picvibe
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.0.5 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  firebase_core: ^2.15.0
  image_editor_plus: ^0.2.5
  lottie: ^2.5.0
  sign_in_button: ^3.2.0
  google_sign_in: ^6.1.4
  get_storage: ^2.1.1
  objectbox: ^2.1.0
  objectbox_flutter_libs: ^2.1.0
  share_plus: ^7.0.2
  path_provider: ^2.0.15
  rename: ^2.1.1
  flutter_launcher_icons: 0.13.1
  flutter: 
    sdk: flutter

dev_dependencies: 
  flutter_lints: ^2.0.0
  build_runner: ^2.4.6
  objectbox_generator: ^2.1.0
  flutter_test: 
    sdk: flutter

flutter_launcher_icons: 
  android: launcher_icon
  image_path: assets/logo/logo.png
  flutter_lints: ^2.0.0
  ios: true
  min_sdk_android: 21

flutter: 
  assets: 
    - assets/logo/
    - assets/lotties/
    - assets/
  uses-material-design: true

