name: zesdro
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=3.0.5 <4.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  get: 4.6.5
  flutter: 
    sdk: flutter
  firebase_core: ^2.15.0
  image_editor_plus: ^0.2.5
  lottie: ^2.5.0
  sign_in_button: ^3.2.0
  google_sign_in: ^6.1.4
  get_storage: ^2.1.1

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter


flutter: 
  assets: 
    - assets/logo/
    - assets/lotties/
    - assets/
  uses-material-design: true

